/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   display.h                                          :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: hsarhan <hsarhan@student.42.fr>            +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2022/12/26 00:39:06 by hsarhan           #+#    #+#             */
/*   Updated: 2022/12/26 00:45:11 by hsarhan          ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#ifndef WINDOW_H
# define WINDOW_H

/**
 * @brief Struct containing information relevant for mlx and the window
 * generated by it
 * @param mlx Pointer to mlx instance
 * @param mlx_win Pointer to mlx window
 * @param img Pointer to image that we will write the pixels to
 * @param addr Pointer to the first pixel of the image
 * @param bytes_per_pixel Bytes per pixel
 * @param line_length Number of pixels in a row
 * @param endian idk
 */
typedef struct s_display			t_display;
struct	s_display
{
	void	*mlx;
	void	*mlx_win;
	void	*edit_img;
	char	*edit_addr;
	void	*display_img;
	char	*display_addr;
	void	*render_img;
	char	*render_addr;
	void	*info_img;
	char	*info_addr;
	int		bytes_per_pixel;
	int		line_length;
	int		endian;
};

#endif